# Generated by Django 3.2.7 on 2021-09-22 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_postlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='authentication.post'),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
